name: FIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build
    - name: Build Release
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false
    - name: Build Wrapper Debug
      run: dotnet build wrapper
    - name: Build Wrapper Release
      run: dotnet publish wrapper -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false
    - name: Upload Debug
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Debug
        path: "Fynns ISO Patcher\\bin\\Debug\\net6.0"
        
    - name: Upload Release
      uses: actions/upload-artifact@v3.0.0
      with:
         name: Release
         path: "Fynns ISO Patcher\\bin\\Release\\net6.0\\win-x64\\publish"
        
    - name: Upload Wrapper Debug
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Wrapper Debug
        path: "Wrapper\\bin\\Debug\\net6.0"
        
    - name: Upload Wrapper Release
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Wrapper Release
        path: "Wrapper\\bin\\Release\\net6.0\\win-x64\\publish"
