name: FIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build
    - name: Publish
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Release --self-contained false
    - name: Zip Debug
      run: Compress-Archive "Fynns ISO Patcher\bin\Debug\net6.0" "Fynns ISO Patcher\bin\Debug\net6.0\FIP_Debug.zip"
    - name: Zip Publish
      run: Compress-Archive "Fynns ISO Patcher\bin\Release\net6.0\win-x64\publish" "Fynns ISO Patcher\bin\Release\net6.0\win-x64\publish\FIP_Publish.zip"
    - name: Upload Debug
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Debug
        path: "Fynns ISO Patcher\\bin\\Debug\\net6.0\\FIP_Debug.zip"
        
    - name: Upload Publish
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Publish
        path: "Fynns ISO Patcher\\bin\\Release\\net6.0\\win-x64\\publish\\FIP_Publish.zip"
